force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <description>Instances of loans managed by the Asset Management Team. Reports and Activities are enabled.</description>
    <label>Loan</label>
    <nameField>
        <displayFormat>LN-{000000}</displayFormat>
        <label>Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Date_Loan_Issued__c.field-meta.xml
<CustomField>
    <fullName>Date_Loan_Issued__c</fullName>
    <description>The original issue date of the loan</description>
    <inlineHelpText>The original issue date of the loan</inlineHelpText>
    <label>Loan Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Loan_Name__c.field-meta.xml
<CustomField>
    <fullName>Loan_Name__c</fullName>
    <description>User-defined name of Loan</description>
    <inlineHelpText>Free-text description used as name of loan</inlineHelpText>
    <label>Loan Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <description>Duration of the Term in months</description>
    <inlineHelpText>Duration of the Term in months</inlineHelpText>
    <label>Loan Term</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Charge__c/Loan_Charge__c.object-meta.xml
<CustomObject>
    <description>Various charges associated with a loan</description>
    <label>Loan Charge</label>
    <nameField>
        <displayFormat>LC-{00000}</displayFormat>
        <label>Loan Charge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Charge__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The value of the charge</description>
    <inlineHelpText>The value of the charge</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Charge__c/fields/Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>Charge_Type__c</fullName>
    <description>Range of charge types</description>
    <inlineHelpText>Select the charge type (only one Release Charge per loan)</inlineHelpText>
    <label>Charge Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Release Charge</fullName>
            </value>
            <value>
                <fullName>Interest Charge</fullName>
            </value>
            <value>
                <fullName>Legal Fee</fullName>
            </value>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Charge__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>The date the charge was applied</description>
    <inlineHelpText>The date the charge was applied</inlineHelpText>
    <label>Charge Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan_Charge__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <description>Master-detail relationship to the loan</description>
    <inlineHelpText>Master-detail relationship to the loan</inlineHelpText>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Loan Charges</relationshipLabel>
    <relationshipName>Loan_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/LoanHelper.cls
//  Helper class for servicing Loan triggers
public class LoanHelper {
 
 // Charge Amounts
    public static final Decimal INIT_REL_AMT = 500.00;
    public static final Decimal ADMIN_AMT = 300.00;
    
    // Create Release Charge for new Loan
    public static void createReleaseCharge (List<Loan__c> insLoans) {

        List<Loan_Charge__c>insLcs = new List<Loan_Charge__c>();
        for (Loan__c ln :insLoans) {
            Loan_Charge__c insLc = new Loan_Charge__c (
                Loan__c = ln.Id,
                Charge_Type__c = 'Release Charge',
                Amount__c = INIT_REL_AMT,
                Date__c = ln.Date_Loan_Issued__c.addMonths((integer)ln.Term__c)
            );
          insLcs.add(insLc);
        }
  	 	insert insLcs;
    }
    // Process Loan Term change on update
    public static void procTermChange (Map<Id,Loan__c> oldLoanMap, List<Loan__c>newLoans) {
        
        Date curDt = Date.Today();
        
        // Find existing Release Charge for all Loans
        Map<ID, Loan_Charge__c> lcRelMap = new Map<ID, Loan_Charge__c>{};
        List<Loan_Charge__c> lcRels = [SELECT Id, Loan__c, Loan__r.Loan_Name__c, Date__c, Amount__c
                                       from Loan_Charge__c
                                       WHERE Charge_Type__c = 'Release Charge'];
         for (Loan_Charge__c lcRelIter : lcRels) {
            lcRelMap.put (lcRelIter.Loan__c, lcRelIter);
        }     
        
        // Find existing Interest Charge for all Loans (ASSUPTION: Only one interest charge per loan per day)
        Map<ID, Loan_Charge__c> lcInMap = new Map<ID, Loan_Charge__c>{};
        List<Loan_Charge__c> lcIns = [SELECT Id, Loan__c, Loan__r.Loan_Name__c, Date__c, Amount__c
                                       from Loan_Charge__c
                                       WHERE Charge_Type__c = 'Interest Charge'
                                       and Date__c = :curDt];
         for (Loan_Charge__c lcInIter : lcIns) {
            lcInMap.put (lcInIter.Loan__c, lcInIter);
        } 
        
        // Loan Charge records to update
        List<Loan_Charge__c>updLcs = new List<Loan_Charge__c>();
        
        // Loan Charge records to insert
        List<Loan_Charge__c>insLcs = new List<Loan_Charge__c>();
        
        for (Loan__c ln : newLoans) {
            Loan__c oldln = oldLoanMap.get(ln.Id);
            if (ln.Term__c <> oldln.Term__c) {
                
               // Update date of linked Release Charge
               if (lcRelMap.containsKey(ln.Id)) { // could have been deleted
                	Loan_Charge__c lcRel = lcRelMap.get(ln.Id);  
                    lcRel.Date__c = ln.Date_Loan_Issued__c.addMonths((integer)ln.Term__c);
                    updLcs.add(lcRel);
                }
                // Create new Loan Charge
                Loan_Charge__c insLc = new Loan_Charge__c (
              	    Charge_Type__c = 'Admin Fee',
                    Loan__c = ln.Id,
                	Amount__c = ADMIN_AMT,
                	Date__c = curDt);
                insLcs.add(insLc);
                
                // Advance interest charge date if found in set for today
                if (lcInMap.containsKey(ln.Id)) {
                   	Loan_Charge__c lcIn = lcInMap.get(ln.Id);  
                   	lcIn.Date__c = curDt + 1;
                   	updLcs.add(lcIn);                 
                }
            }
        }
        update updLcs;  
        insert insLcs;
    }
}