force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <description>Instances of loans managed by the Asset Management Team. Reports and Activities are enabled.</description>
    <label>Loan</label>
    <nameField>
        <displayFormat>LN-{000000}</displayFormat>
        <label>Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Person Account record holding the loan</description>
    <inlineHelpText>The individual holding the loan</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Date_Loan_Issued__c.field-meta.xml
<CustomField>
    <fullName>Date_Loan_Issued__c</fullName>
    <description>The original issue date of the loan</description>
    <inlineHelpText>The original issue date of the loan</inlineHelpText>
    <label>Loan Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Gross_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Gross_Loan_Amount__c</fullName>
    <description>Initial total amount of the loan</description>
    <inlineHelpText>Initial total amount of the loan</inlineHelpText>
    <label>Gross Loan Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Loan_Name__c.field-meta.xml
<CustomField>
    <fullName>Loan_Name__c</fullName>
    <description>User-defined name of Loan</description>
    <inlineHelpText>Free-text description used as name of loan</inlineHelpText>
    <label>Loan Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <description>Duration of the Term in months</description>
    <inlineHelpText>Duration of the Term in months</inlineHelpText>
    <label>Loan Term</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Charge__c/Loan_Charge__c.object-meta.xml
<CustomObject>
    <description>Various charges associated with a loan</description>
    <label>Loan Charge</label>
    <nameField>
        <displayFormat>LC-{00000}</displayFormat>
        <label>Loan Charge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Charge__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The value of the charge</description>
    <inlineHelpText>The value of the charge</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Charge__c/fields/Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>Charge_Type__c</fullName>
    <description>Range of charge types</description>
    <inlineHelpText>Select the charge type (only one Release Charge per loan)</inlineHelpText>
    <label>Charge Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Release Charge</fullName>
            </value>
            <value>
                <fullName>Interest Charge</fullName>
            </value>
            <value>
                <fullName>Legal Fee</fullName>
            </value>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Charge__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>The date the charge was applied</description>
    <inlineHelpText>The date the charge was applied</inlineHelpText>
    <label>Charge Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan_Charge__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <description>Master-detail relationship to the loan</description>
    <inlineHelpText>Master-detail relationship to the loan</inlineHelpText>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Loan Charges</relationshipLabel>
    <relationshipName>Loan_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/LoanHelperTest.cls
// Test class for Loan and Loan Charge processing
@isTest
private class LoanHelperTest {
    
    @isTest 
    private static void newLoanTest () {
 	
    	// Create Person Account with record type
		Account tstAcc = creAcc();
    
    	Date curDt = Date.Today();
    	Integer LnTerm = 24;
    	Date endDt = curDt.addMonths(lnTerm);
    
    	Loan__c tstLn = new Loan__c (
            Loan_Name__c = 'Test Loan',
    		Account__c = tstAcc.Id,
        	Gross_Loan_Amount__c = 300000,
        	Date_Loan_Issued__c = curDt,
        	Term__c = lnTerm
    	);
        Test.startTest();
        insert tstLn;
    	Test.stopTest();
    
    	List<Loan_Charge__c> tstLcs = [SELECT Id from Loan_Charge__c 
                                       where Loan__c = :tstLn.Id 
                                       and Charge_Type__c = 'Release Charge' 
                                       and Date__c = :endDt];
    	Assert.areEqual(1, tstLcs.Size(), 'Must be 1 Release Charge with calculated charge date');
    }      
    @isTest 
    private static void updChargeTest () {
        Account tstAcc = creAcc();
        
      	Date curDt = Date.Today();
    	Integer LnTerm = 24;
        Integer modTerm = 36;
    	Date modDt = curDt.addMonths(modTerm);
    
    	Loan__c tstLn = new Loan__c (
            Loan_Name__c = 'Test Loan',
    		Account__c = tstAcc.Id,
        	Gross_Loan_Amount__c = 300000,
        	Date_Loan_Issued__c = curDt,
        	Term__c = lnTerm
    	);
        insert tstLn;
        
        // Test the case where there is an Interest Charge
        Loan_Charge__c insLc = new Loan_Charge__c (
                Loan__c = tstLn.Id,
                Charge_Type__c = 'Interest Charge',
                Amount__c = 200,
                Date__c = curDt
        );
        insert insLc;    

        Date intDt = curDt + 1;
        Test.startTest();
        tstLn.Term__c = modTerm;
        update tstLn;
    	Test.stopTest();

        // Check for updated Release Charge
     	List<Loan_Charge__c> tstRelLcs = [SELECT Id from Loan_Charge__c 
                                       where Loan__c = :tstLn.Id 
                                       and Charge_Type__c = 'Release Charge' 
                                       and Date__c = :modDt];
    	Assert.areEqual(1, tstRelLcs.Size(), 'Must be 1 Release Charge with revised date for Term' );
        
        // Check for Admin charge
     	List<Loan_Charge__c> tstAdmLcs = [SELECT Id from Loan_Charge__c 
                                       where Loan__c = :tstLn.Id 
                                       and Charge_Type__c = 'Admin Fee' 
                                       and Date__c = :curDt];
    	Assert.areEqual(1, tstAdmLcs.Size(), 'Must be 1 Admin Charge for today');

       // Check for Interest charge
     	List<Loan_Charge__c> tstIntLcs = [SELECT Id from Loan_Charge__c 
                                       where Loan__c = :tstLn.Id 
                                       and Charge_Type__c = 'Interest Charge' 
                                       and Date__c = :intDt];
    	Assert.areEqual(1, tstIntLcs.Size(), 'Must be 1 Interest Charge for incremented day');
    }
    @isTest 
             
 // Test the case where there is an duplicate Release Charge
    private static void dupRelTest () {
         Account tstAcc = creAcc();
        
         Date curDt = Date.Today();
    	 Integer LnTerm = 24;
        
         Loan__c tstLn = new Loan__c (
            Loan_Name__c = 'Test Loan',
    		Account__c = tstAcc.Id,
        	Gross_Loan_Amount__c = 300000,
        	Date_Loan_Issued__c = curDt,
        	Term__c = lnTerm
    	);
        insert tstLn;
 
        Loan_Charge__c insLc = new Loan_Charge__c (
                Loan__c = tstLn.Id,
                Charge_Type__c = 'Release Charge',
                Amount__c = 500,
                Date__c = curDt.addMonths(LnTerm)
        );
		Boolean hasException = false;
        Test.startTest();
		// Try-catch gives coverage of the thrown exception but Database.SaveResult does not.
        try {
            insert insLc;
        }
        catch (Exception e) {
            hasException = true; 
        	System.debug('Caught exception ' + e.getMessage());
        }
		Test.stopTest();
        
        Assert.isTrue (hasException, 'Exception should be generated');
    }
    
     // Test the case where the date has to be extended
    @isTest
    private static void lateDateTest () {
         Account tstAcc = creAcc();
        
         Date curDt = Date.Today();
    	 Integer LnTerm = 24;
         Date lateDt = curDt.addMonths(lnTerm) + 7;
         Date extendedDt = curDt.addMonths(lnTerm).addMonths(1);
        
         Loan__c tstLn = new Loan__c (
            Loan_Name__c = 'Test Loan',
    		Account__c = tstAcc.Id,
        	Gross_Loan_Amount__c = 300000,
        	Date_Loan_Issued__c = curDt,
        	Term__c = lnTerm
    	);
        insert tstLn;
        
        Loan_Charge__c insLc = new Loan_Charge__c (
                Loan__c = tstLn.Id,
                Charge_Type__c = 'Legal Fee',
                Amount__c = 500,
                Date__c = lateDt
        );
        Test.startTest();
        insert insLc;
        Test.stopTest();

        // Check for updated Release Charge
     	List<Loan_Charge__c> tstRelLcs = [SELECT Id from Loan_Charge__c 
                                       where Loan__c = :tstLn.Id 
                                       and Charge_Type__c = 'Release Charge' 
                                       and Date__c = :extendedDt];
    	Assert.areEqual(1, tstRelLcs.Size(), 'Must be 1 Release Charge with extended date for late Charge' );
       
    }
     
    // Method to set up a Person Account
    private static Account creAcc() {

        // Create Person Account with record type
	  	Id PAccRecId =  Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
 		Account tstAcc = new Account(
	 		FirstName = 'Loan',
 			LastName = 'Loaner',
 			RecordTypeId = PAccRecId
    	);
 		insert tstAcc;
        return tstAcc;
    }
}