force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <description>Instances of loans managed by the Asset Management Team. Reports and Activities are enabled.</description>
    <label>Loan</label>
    <nameField>
        <displayFormat>LN-{000000}</displayFormat>
        <label>Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Loan_Name__c.field-meta.xml
<CustomField>
    <fullName>Loan_Name__c</fullName>
    <description>User-defined name of Loan</description>
    <inlineHelpText>Free-text description used as name of loan</inlineHelpText>
    <label>Loan Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Charge__c/Loan_Charge__c.object-meta.xml
<CustomObject>
    <description>Various charges associated with a loan</description>
    <label>Loan Charge</label>
    <nameField>
        <displayFormat>LC-{00000}</displayFormat>
        <label>Loan Charge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Charge__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The value of the charge</description>
    <inlineHelpText>The value of the charge</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Charge__c/fields/Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>Charge_Type__c</fullName>
    <description>Range of charge types</description>
    <inlineHelpText>Select the charge type (only one Release Charge per loan)</inlineHelpText>
    <label>Charge Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Release Charge</fullName>
            </value>
            <value>
                <fullName>Interest Charge</fullName>
            </value>
            <value>
                <fullName>Legal Fee</fullName>
            </value>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Charge__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>The date the charge was applied</description>
    <inlineHelpText>The date the charge was applied</inlineHelpText>
    <label>Charge Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan_Charge__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <description>Master-detail relationship to the loan</description>
    <inlineHelpText>Master-detail relationship to the loan</inlineHelpText>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Loan Charges</relationshipLabel>
    <relationshipName>Loan_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/LoanChargeHelper.cls
// Helpers to handle loan charge constraint and date propagation
public class LoanChargeHelper {
    public class RelException extends Exception {}
    
    // Method to cover all restrictions and actions relating to existing Release Charges
    public static void chkReleaseCharge (List<Loan_Charge__c> insLcs, Map<Id,Loan_Charge__c>insLcMap) {
        
        // For excluding uncommitted records on initial insert
		Set<Id>insIds = insLcMap.keyset();
        
        // Fetch all the existing Release Charge record for both types of new Loan Charge cases
        Map<ID, Loan_Charge__c> lcRelMap = new Map<ID, Loan_Charge__c>{};
        List<Loan_Charge__c> lcRels = [SELECT Id, Loan__c, Loan__r.Loan_Name__c, Date__c, Amount__c
                                       from Loan_Charge__c
                                       WHERE Charge_Type__c = 'Release Charge'
                                       and (NOT Id in :insIds)];
        // Loan Charge records to update
        List<Loan_Charge__c>updRels = new List<Loan_Charge__c>();
        
        for (Loan_Charge__c lcRel : lcRels) {
            lcRelMap.put (lcRel.Loan__c, lcRel);
        }
 
        // Enforce constraint of one Release Charge
        for (Loan_Charge__c lc :insLcs) {
            if (lc.Charge_Type__c == 'Release Charge') {
            	if (lcRelMap.containsKey(lc.Loan__c)) {
                    Loan_Charge__c lcRel = lcRelMap.get(lc.Loan__c);
                    throw new RelException('Attempt to insert duplicate Release Charge for loan ' + lcRel.Loan__r.Loan_Name__c); 
                }
            }
            
			// For other types apply date extension if needed
            else {
                if (lcRelMap.containsKey(lc.Loan__c)) { // could have been deleted
                	Loan_Charge__c lcRel = lcRelMap.get(lc.Loan__c);  
                    if (lc.Date__c > lcRel.Date__c ) {
                        lcRel.Date__c = LcRel.Date__c.addMonths(1);
                        updRels.add(lcRel);
                    }
                }
                // Balance is updated by formula
            }
        }
        // Run all the updates in bulk
        update updRels;
    }
}